[package]
name = "server-sent_events"
version = "0.0.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2021"
description = "Server-Sent Events (SSE)"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/bk-rs/sse-rs"
homepage = "https://github.com/bk-rs/sse-rs"
documentation = "https://docs.rs/server-sent_events"
keywords = []
categories = []
readme = "README.md"

[dependencies]
